# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example_video.mp3"
Content-Type: mp3/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/81f912e1-2a81-4b59-8900-496d998cf645/transcription
Content-Type: application/json

{
    "prompt": "sound effects"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "81f912e1-2a81-4b59-8900-496d998cf645",
    "temperature": 0.5,
    "prompt": "Generate a summary of the transcription from the : '''{transcription}'''" 
}